### ISSUE TITLE
Wrong Creature Error

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#30]
I have a new error message appearing on transfer Creatures

12:51:11 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (F:\snapshot\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
12:51:11 - error:  __type=FServiceError, args=[], cause=WRONG_CREATURE

I also have this error code

(node:33732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by niicojs** [comment]
does this happend to all creature or specific one?

**Comment by mitviet1** [comment]
WRONG_CREATURE error showing up is when you tried to transfer a creature but that creature is either already placed in a gym or in a library or it is marked as 'favorite'.  So I don't think that is really an error but simply the msg to tell you that you can't transfer them because of those 3 condition.

**Comment by niicojs** [comment]
Ok good info. I'll have a look

**Comment by Nackenschelle** [comment]
ok thanks for the info

**Comment by niicojs** [comment]
if you can test, should be better
